name: Build Executables

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [main]

jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Create Windows Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          path: src
          python_ver: '3.11'
          pyinstaller_ver: '==5.13.2'
          spec: 'src/vpem.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'vpem-windows'
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/vpem-windows/vpem-windows.exe

  pyinstaller-build-macos-x86:
    runs-on: macos-latest
    steps:
      - name: Create macOS x86 Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          path: src
          python_ver: '3.11'
          pyinstaller_ver: '==5.13.2'
          spec: 'src/vpem.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'vpem-macos-x86'
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/vpem-macos-x86/vpem-macos-x86

  pyinstaller-build-macos-arm:
    runs-on: macos-latest
    steps:
      - name: Create macOS ARM Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          path: src
          python_ver: '3.11'
          pyinstaller_ver: '==5.13.2'
          spec: 'src/vpem.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'vpem-macos-arm'
          options: --target-arch arm64
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/vpem-macos-arm/vpem-macos-arm

  pyinstaller-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Linux x64 Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          path: src
          python_ver: '3.11'
          pyinstaller_ver: '==5.13.2'
          spec: 'src/vpem.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'vpem-linux-x64'
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/vpem-linux-x64/vpem-linux-x64
