name: Build Executables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Create Windows Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          pyinstaller_ver: '==5.13.2'
          spec: 'vpem.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'vpem-windows'

  pyinstaller-build-macos-x86:
    runs-on: macos-latest
    steps:
      - name: Create macOS x86 Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          pyinstaller_ver: '==5.13.2'
          spec: 'vpem.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'vpem-macos-x86'

  pyinstaller-build-macos-arm:
    runs-on: macos-latest
    steps:
      - name: Create macOS ARM Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          pyinstaller_ver: '==5.13.2'
          spec: 'vpem.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'vpem-macos-arm'
          options: --target-arch arm64

  pyinstaller-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Linux x64 Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          pyinstaller_ver: '==5.13.2'
          spec: 'vpem.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'vpem-linux-x64'
